site_name: DCS Documentation
use_directory_urls: false
theme:
  name: material
  palette:
    # Follow the user's OS preference on first visit.
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light palette.
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark palette.
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_source: true # Adds "view source" links pointing to the file & line number in your repo
            show_submodules: true # Recursively documents submodules under the main package/module
            # show_if_no_docstring: true  # Renders members even if they have no docstring (shows at least the name/signature)
            show_root_heading: true # Adds a top-level heading for the root object/module on the page
            show_root_toc_entry: true # Adds that root heading to the page's table of contents for navigation
nav:
  - Home: index.md

  - Getting Started: getting_started.md

  - User Guide:
      - Overview: user_guide/overview.md
      - Configuration: user_guide/configuration.md
      - Running Locally: user_guide/running_locally.md
      - Playing Games: user_guide/playing.md
      - Analyzing Results: user_guide/analyzing_results.md
      - Deployment: user_guide/deployment.md

  - Use Cases:
      - Researcher Running a Study: use_cases/general-researcher.md
      - AI Practitioner Evaluating an Agent: use_cases/ai-researcher.md
      - Educator / Training Session: use_cases/educator.md

  - Design:
      - Overview: design/overview.md
      - Games: design/games.md
      - Characters: design/characters.md

  - Studies:
      - Overview: studies/overview.md
      - Usability: studies/usability.html
      - Simulation Quality: studies/simulation_quality.html
      - Performance Benchmarking: studies/performance_benchmarking.html

  - Codebase Reference: codebase_reference.md
  - Examples: examples.md
  - API Docs: "https://dcs-free-play-api.fly.dev/redoc"
  - Tags: tags.md
  - FAQ: faq.md
