"""initial schema

Revision ID: f68d8965d452
Revises: 
Create Date: 2026-03-05 23:59:01.775747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68d8965d452'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hid', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.Column('common_descriptors', sa.JSON(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('anthronormal_divergence', sa.JSON(), nullable=True),
    sa.Column('interaction_examples', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_hid'), 'characters', ['hid'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_revoked', sa.Boolean(), nullable=False),
    sa.Column('last_key_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prior_experience', sa.Text(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('consent_to_followup', sa.Text(), nullable=True),
    sa.Column('consent_signature', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.Text(), nullable=True),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth', ['user_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('game_config', sa.JSON(), nullable=True),
    sa.Column('default_model_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['default_model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_default_model_id'), 'games', ['default_model_id'], unique=False)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('pii',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pii_email'), 'pii', ['email'], unique=False)
    op.create_index(op.f('ix_pii_user_id'), 'pii', ['user_id'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('pc_character_id', sa.Uuid(), nullable=True),
    sa.Column('npc_character_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('lifecycle', sa.String(length=50), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('exited', sa.Boolean(), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('stopping_conditions', sa.JSON(), nullable=True),
    sa.Column('scratchpad', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['npc_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pc_character_id'], ['characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_game_id'), 'sessions', ['game_id'], unique=False)
    op.create_index(op.f('ix_sessions_player_id'), 'sessions', ['player_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_session_id'), 'feedback', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('validator_response', sa.JSON(), nullable=True),
    sa.Column('updater_response', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_model_id'), 'messages', ['model_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_model_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_feedback_session_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_sessions_player_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_game_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_pii_user_id'), table_name='pii')
    op.drop_index(op.f('ix_pii_email'), table_name='pii')
    op.drop_table('pii')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_default_model_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth')
    op.drop_table('auth')
    op.drop_table('users')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_characters_hid'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
